const options = {
  lang: "auto",
  background: "rgba(171, 184, 195, 1)",
  theme: "dracula",
  font: "Hack",
  "window-controls": true,
  "width-adjustment": true,
  line: true,
  "first-line": 1,
  watermark: false,
};

const themes = [
  "a11y-dark",
  "atom-dark",
  "base16-ateliersulphurpool.light",
  "cb",
  "darcula",
  "default",
  "dracula",
  "duotone-dark",
  "duotone-earth",
  "duotone-forest",
  "duotone-light",
  "duotone-sea",
  "duotone-space",
  "ghcolors",
  "hopscotch",
  "material-dark",
  "material-light",
  "material-oceanic",
  "nord",
  "pojoaque",
  "shades-of-purple",
  "synthwave84",
  "vs",
  "vsc-dark-plus",
  "xonokai",
];

const langs = [
  "auto",
  "c",
  "css",
  "cpp",
  "go",
  "html",
  "java",
  "javascript",
  "jsx",
  "php",
  "python",
  "rust",
  "typescript",
];

const fonts = [
  "MonoLisa",
  "Anonymouse-Pro",
  "Cascadia-Code",
  "Droid-Sans-Mono",
  "Fantasque-Sans-Mono",
  "Fira-Code",
  "Hack",
  "IBM-Flex-Mono",
  "Inconsolata",
  "JetBrains-Mono",
  "Monoid",
  "Source-Code-Pro",
  "Space-Mono",
  "Ubuntu-Mono",
];

module.exports = { options, themes, langs, fonts };
